### ISSUE TITLE
packt-cli always downloads to the same location as the first time, also ignores symlinks

### ISSUE THREAD

**Issue by dennisdenk** [luk6xff/Packt-Publishing-Free-Learning#139]
![grafik](https://user-images.githubusercontent.com/19978270/54724957-8c5e0080-4b6d-11e9-8a1a-4847c9e19c40.png)

**Comment by mjenczmyk** [comment]
It's because `-f` parameter is a boolean flag - its value decides whether different formats of the same ebook should be downloaded to separate directory inside download directory or directly to download directory.

What you're looking for is the possibility to change download directory - you can do this in the configuration file (which probably isn't the most intuitive place), I'd prefer to have it available as CLI parameter.
